"""
Core foundation module for the Autonomous Algorithmic Trading System.

Exports all public types, configurations, exceptions, utilities, and loggers.
"""

from core.config import (
    BinanceConfig,
    TradingConfig,
    StrategyConfig,
    BacktestConfig,
    LiveTradingConfig,
    Config,
)
from core.types import (
    Candle,
    Signal,
    Position,
    Order,
    Account,
    Trade,
    Ticker,
    OrderBook,
    BacktestMetrics,
    EquityCurve,
    SignalType,
    OrderSide,
    OrderStatus,
    PositionStatus,
    StrategyType,
    TimeFrame,
)
from core.exceptions import (
    TradingException,
    ConfigurationError,
    APIError,
    MarketDataError,
    StrategyError,
    RiskManagementError,
    ExecutionError,
    BacktestError,
    # Specific exceptions
    InvalidConfigError,
    MissingCredentialsError,
    ConnectionError as TradingConnectionError,
    RateLimitError,
    AuthenticationError,
    InsufficientDataError,
    DataValidationError,
    InvalidSignalError,
    InsufficientStrategyDataError,
    PositionRejectedError,
    MaxDrawdownExceededError,
    DailyLossExceededError,
    OrderPlacementError,
    OrderTimeoutError,
    DataLoadError,
    LookAheadBiasError,
    is_critical_error,
    is_retryable_error,
)
from core.logger import (
    Logger,
    TradeLogger,
    PerformanceLogger,
    StrategyLogger,
    RiskLogger,
    trade_logger,
    performance_logger,
    strategy_logger,
    risk_logger,
)
from core.utils import (
    calculate_kelly_fraction,
    calculate_position_size,
    calculate_sharpe_ratio,
    calculate_sortino_ratio,
    calculate_max_drawdown,
    calculate_win_rate,
    calculate_profit_factor,
    calculate_sma,
    calculate_ema,
    calculate_bollinger_bands,
    calculate_atr,
    calculate_rsi,
    calculate_adx,
)

__all__ = [
    # Config
    "BinanceConfig",
    "TradingConfig",
    "StrategyConfig",
    "BacktestConfig",
    "LiveTradingConfig",
    "Config",
    # Types
    "Candle",
    "Signal",
    "Position",
    "Order",
    "Account",
    "Trade",
    "Ticker",
    "OrderBook",
    "BacktestMetrics",
    "EquityCurve",
    "SignalType",
    "OrderSide",
    "OrderStatus",
    "PositionStatus",
    "StrategyType",
    "TimeFrame",
    # Exceptions
    "TradingException",
    "ConfigurationError",
    "APIError",
    "MarketDataError",
    "StrategyError",
    "RiskManagementError",
    "ExecutionError",
    "BacktestError",
    "InvalidConfigError",
    "MissingCredentialsError",
    "TradingConnectionError",
    "RateLimitError",
    "AuthenticationError",
    "InsufficientDataError",
    "DataValidationError",
    "InvalidSignalError",
    "InsufficientStrategyDataError",
    "PositionRejectedError",
    "MaxDrawdownExceededError",
    "DailyLossExceededError",
    "OrderPlacementError",
    "OrderTimeoutError",
    "DataLoadError",
    "LookAheadBiasError",
    "is_critical_error",
    "is_retryable_error",
    # Loggers
    "Logger",
    "TradeLogger",
    "PerformanceLogger",
    "StrategyLogger",
    "RiskLogger",
    "trade_logger",
    "performance_logger",
    "strategy_logger",
    "risk_logger",
    # Utils
    "calculate_kelly_fraction",
    "calculate_position_size",
    "calculate_sharpe_ratio",
    "calculate_sortino_ratio",
    "calculate_max_drawdown",
    "calculate_win_rate",
    "calculate_profit_factor",
    "calculate_sma",
    "calculate_ema",
    "calculate_bollinger_bands",
    "calculate_atr",
    "calculate_rsi",
    "calculate_adx",
]
