"""
Core data types for the trading system.
All structures are immutable dataclasses with validation.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum


# Enumerations
class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderSide(Enum):
    LONG = "LONG"   # Buy to open
    SHORT = "SHORT" # Sell to open


class OrderStatus(Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PositionStatus(Enum):
    OPENING = "OPENING"     # Order placed, not yet filled
    OPEN = "OPEN"           # Fully filled, active
    CLOSING = "CLOSING"     # Exit order placed
    CLOSED = "CLOSED"       # Fully closed
    REJECTED = "REJECTED"


class StrategyType(Enum):
    MEAN_REVERSION = "MEAN_REVERSION"
    MOMENTUM = "MOMENTUM"
    HYBRID = "HYBRID"


class TimeFrame(Enum):
    ONE_MINUTE = "1m"
    FIVE_MINUTE = "5m"
    FIFTEEN_MINUTE = "15m"
    ONE_HOUR = "1h"
    FOUR_HOUR = "4h"
    ONE_DAY = "1d"


# Data classes
@dataclass(frozen=True)
class Candle:
    """OHLCV candle data."""
    timestamp: int            # Unix milliseconds
    open: float
    high: float
    low: float
    close: float
    volume: float
    quote_asset_volume: float
    interval: TimeFrame = TimeFrame.ONE_MINUTE

    def __post_init__(self):
        if self.high < self.open or self.high < self.close or self.high < self.low:
            raise ValueError("high must be >= open, close, low")
        if self.low > self.open or self.low > self.close or self.low > self.high:
            raise ValueError("low must be <= open, close, high")
        if self.volume < 0:
            raise ValueError("volume cannot be negative")

    def typical_price(self) -> float:
        """Typical price = (high + low + close) / 3."""
        return (self.high + self.low + self.close) / 3.0


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by a strategy."""
    timestamp: int
    strategy: StrategyType
    symbol: str
    signal_type: SignalType
    confidence: float          # 0.0 to 1.0
    entry_price: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    reason: str = ""

    def __post_init__(self):
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0 and 1")
        if self.signal_type == SignalType.HOLD:
            if self.entry_price is not None or self.stop_loss_price is not None:
                raise ValueError("HOLD signals should not have price targets")


@dataclass
class Position:
    """Active trading position."""
    symbol: str
    side: OrderSide
    entry_price: float
    quantity: float            # Base asset amount (e.g., SOL)
    leverage: float
    entry_time: int            # Unix milliseconds
    status: PositionStatus = PositionStatus.OPEN
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    exit_price: Optional[float] = None
    exit_time: Optional[int] = None
    realized_pnl: float = 0.0
    order_id: Optional[str] = None

    @property
    def notional_value(self) -> float:
        """Position size in quote currency (USDT)."""
        return self.quantity * self.entry_price * self.leverage

    def unrealized_pnl(self, current_price: float) -> float:
        """Unrealized PnL in USDT."""
        if self.side == OrderSide.LONG:
            pnl = (current_price - self.entry_price) * self.quantity
        else:  # SHORT
            pnl = (self.entry_price - current_price) * self.quantity
        return pnl * self.leverage

    def close(self, exit_price: float, exit_time: int) -> None:
        """Close the position."""
        self.exit_price = exit_price
        self.exit_time = exit_time
        self.status = PositionStatus.CLOSED
        if self.side == OrderSide.LONG:
            self.realized_pnl = (exit_price - self.entry_price) * self.quantity
        else:
            self.realized_pnl = (self.entry_price - exit_price) * self.quantity
        self.realized_pnl *= self.leverage


@dataclass
class Order:
    """Order placed on exchange."""
    order_id: str
    symbol: str
    side: OrderSide
    quantity: float
    price: float
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    average_fill_price: Optional[float] = None
    created_time: int = field(default_factory=lambda: int(datetime.now().timestamp() * 1000))
    updated_time: Optional[int] = None

    @property
    def is_filled(self) -> bool:
        return self.status == OrderStatus.FILLED

    @property
    def remaining_quantity(self) -> float:
        return self.quantity - self.filled_quantity


@dataclass
class Account:
    """Account information."""
    total_equity: float       # Total USDT value (including unrealized PnL)
    available_balance: float  # Free USDT for new positions
    used_margin: float        # Currently locked margin
    unrealized_pnl: float
    daily_pnl: float          # Today's realized PnL
    peak_equity: float        # Highest equity seen (for drawdown)

    def update_equity(self, new_equity: float) -> None:
        self.total_equity = new_equity
        if new_equity > self.peak_equity:
            self.peak_equity = new_equity

    def current_drawdown_pct(self) -> float:
        if self.peak_equity == 0:
            return 0.0
        return (self.peak_equity - self.total_equity) / self.peak_equity


@dataclass
class Trade:
    """Completed trade record."""
    timestamp: int
    symbol: str
    strategy: StrategyType
    side: OrderSide
    entry_price: float
    exit_price: float
    quantity: float
    realized_pnl: float
    pnl_percent: float
    duration_seconds: int
    entry_reason: str
    exit_reason: str


@dataclass
class Ticker:
    """Real-time ticker data."""
    symbol: str
    bid: float
    ask: float
    last_price: float
    volume_24h: float
    high_24h: float
    low_24h: float


@dataclass
class OrderBook:
    """Order book snapshot."""
    symbol: str
    bids: List[tuple]   # [(price, quantity), ...]
    asks: List[tuple]
    timestamp: int


@dataclass
class BacktestMetrics:
    """Performance metrics from backtest."""
    total_return: float
    sharpe_ratio: float
    max_drawdown: float
    win_rate: float
    profit_factor: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    avg_win: float
    avg_loss: float
    avg_trade_duration_seconds: float
    final_equity: float
    initial_equity: float


@dataclass
class EquityCurve:
    """Equity over time for plotting."""
    timestamps: List[int]
    equities: List[float]
    drawdowns: List[float]
